give_money_every_second: 600
afk_payout: false
#You can add more payouts by copy and paste them. Don't forget to change the numbers!
store-money-in-bank: false
#Set choose-payout-by-chance to true in order to choose the payouts by chances. Replace the "permission" to "chance", e.g. chance: 20. 
choose-payout-by-chance: false
payouts:
  1:
    payout_amount: 50
    max_payout_per_day: 1000
    #chance: 10
    permission:
  2:
    payout_amount: 100
    max_payout_per_day: 10000
    commands:
      - /give %player% diamond 1
    #chance: 90
    permission: tim.vip
message: "&aYou earned &c%money% &afor 10 minutes online time!"
message_payoutlimit_reached: "&cYou have reached the payout limit today. You earned 0$"
message_afk: "&cYou havn't earned money because you were afk!"
message_actionbar: "&aYou earned &c%money% &afor 10 minutes online time!"
message_payoutlimit_reached_actionbar: "&cYou have reached the payout limit today. You got 0$"
message_afk_actionbar: "&cYou havn't earned money because you were afk!"
display-messages-in-chat: true
display-messages-in-actionbar: true
display-messages-in-actionbar-time: 10
#ATM -> Place down a sign with [atm] on the first line to use it!
message_atm_noperms: "&cYou don't have the permission to use ATM's!"
message_atm_nomoneyinbank: "&cYou don't have enough money in bank!"
message_atm_nomoney: "&cYou don't have enough money!"
atm_title: "&cATM"
atm_withdraw: "&cWithdraw"
atm_deposit: "&cDeposit"
atm_balance: "&cBank balance:"
auto-update: true
debug-log: false
configuration-version: 12
